### PR TITLE
Update the names of the form fields

### PR DESCRIPTION
**Pull request by briandant**
I just got annoyed with my poor titling conventions.
You'd think, as an EFL (English as a First Language),
these kind of mistakes would be long gone. But alas,
here we are.

And that `geckodriver.log` 🤦‍♂️

### CODE REVIEW

**Comment by OmarIthawi** [comment]
As an ESL (English as a Second Language), this is re-assuring :joy:

**Review by OmarIthawi — APPROVED** [review]
Thank you @briandant! LGTM.

**Comment by OmarIthawi** [comment]
@briandant could we please merge/close this long running PR?

**Comment by briandant** [comment]
Thanks for the reminder, Omar!

**Pull request closed without merging**
