### PR TITLE
add a TravisCI badge to the README

### PR DESCRIPTION
**Pull request by thraxil**
everyone loves badges.

### CODE REVIEW

**Review by OmarIthawi — APPROVED** [review]
I do! Thanks!

**Review by briandant — APPROVED** [review]
Thanks, again! Happy to have this in our repo. 

Now, you know I have to ask: when will all this goodness be inmplemented also in the AVL repo? ;)

**Comment by thraxil** [comment]
@briandant don't you already have codeship badges in AVL?

**Comment by briandant** [comment]
Hah, yes we do!  Been a while since I looked at the README, obviously.

**Pull request merged**
