### PR TITLE
Improve the install and usage docs

### PR DESCRIPTION
**Pull request by briandant**

### CODE REVIEW

**Comment by tomaszzielinski** [comment]
@briandant I'm not sure whether this is ready for a review or not?

**Comment by briandant** [comment]
@tomaszzielinski: Nope, not ready! I missed this one when I threw a rebase party last week. Fixing now.

**Comment by briandant** [comment]
Okay @tomaszzielinski, this should now be a little more reviewer friendly. :-P

**Review by tomaszzielinski — APPROVED** [review]

**Pull request merged**
